# This file is automatically managed by <https://github.com/dtinth/jslibdevkit>.
# Any manual changes to this file may be overwritten.

# Publishing to npm will be done by GitHub Actions — see `.github/workflows/publish.yml`.
npm: false

github:
  release: true

plugins:
  news-fragments:
    fragmentsFolder: changes
