# This file is automatically managed by <https://github.com/dtinth/jslibdevkit>.
# Any manual changes to this file may be overwritten.

github:
  release: true
plugins:
  news-fragments:
    fragmentsFolder: changes
